import { useState } from "react";
import "./App.css";

import { Navbar } from "./components/Navbar";

import {
  brann,
  brannHP1,
  brannHP2,
  brannHP3,
  brannST1,
  brannST2,
  brannST3,
  brannST4,
  brannST5,
  brannST6,
  demon_hunter,
  demon_hunterHP1,
  demon_hunterHP2,
  demon_hunterHP3,
  demon_hunterST1,
  demon_hunterST2,
  demon_hunterST3,
  demon_hunterST4,
  demon_hunterST5,
  demon_hunterST6,
  drekthar,
  drektharHP1,
  drektharHP2,
  drektharHP3,
  drektharST1,
  drektharST2,
  drektharST3,
  drektharST4,
  drektharST5,
  drektharST6,
  druid,
  druidHP1,
  druidHP2,
  druidHP3,
  druidST1,
  druidST2,
  druidST3,
  druidST4,
  druidST5,
  druidST6,
  elise,
  eliseHP1,
  eliseHP2,
  eliseHP3,
  eliseST1,
  eliseST2,
  eliseST3,
  eliseST4,
  eliseST5,
  eliseST6,
  finley,
  finleyHP1,
  finleyHP2,
  finleyHP3,
  finleyST1,
  finleyST2,
  finleyST3,
  finleyST4,
  finleyST5,
  finleyST6,
  hunter,
  hunterHP1,
  hunterHP2,
  hunterHP3,
  hunterST1,
  hunterST2,
  hunterST3,
  hunterST4,
  hunterST5,
  hunterST6,
  mage,
  mageHP1,
  mageHP2,
  mageHP3,
  mageST1,
  mageST2,
  mageST3,
  mageST4,
  mageST5,
  mageST6,
  paladin,
  paladinHP1,
  paladinHP2,
  paladinHP3,
  paladinST1,
  paladinST2,
  paladinST3,
  paladinST4,
  paladinST5,
  paladinST6,
  priest,
  priestHP1,
  priestHP2,
  priestHP3,
  priestST1,
  priestST2,
  priestST3,
  priestST4,
  priestST5,
  priestST6,
  reno,
  renoHP1,
  renoHP2,
  renoHP3,
  renoST1,
  renoST2,
  renoST3,
  renoST4,
  renoST5,
  renoST6,
  rogue,
  rogueHP1,
  rogueHP2,
  rogueHP3,
  rogueST1,
  rogueST2,
  rogueST3,
  rogueST4,
  rogueST5,
  rogueST6,
  shaman,
  shamanHP1,
  shamanHP2,
  shamanHP3,
  shamanST1,
  shamanST2,
  shamanST3,
  shamanST4,
  shamanST5,
  shamanST6,
  vanndar,
  vanndarHP1,
  vanndarHP2,
  vanndarHP3,
  vanndarST1,
  vanndarST2,
  vanndarST3,
  vanndarST4,
  vanndarST5,
  vanndarST6,
  warlock,
  warlockHP1,
  warlockHP2,
  warlockHP3,
  warlockST1,
  warlockST2,
  warlockST3,
  warlockST4,
  warlockST5,
  warlockST6,
  warrior,
  warriorHP1,
  warriorHP2,
  warriorHP3,
  warriorST1,
  warriorST2,
  warriorST3,
  warriorST4,
  warriorST5,
  warriorST6,
} from "./Images/index";

function App() {
  const [heroes] = useState([
    {
      id: 1,
      heroName: "Brann",
      class: "Brann",
      heroPower: brannHP1,
      hpSelect: {
        option1: brannHP1,
        name1: "Scattershot",
        option2: brannHP2,
        name2: "Well Equipped",
        option3: brannHP3,
        name3: "Dino Tracking",
      },
      sigTreasure: brannST1,
      stSelect: {
        option1: brannST1,
        name1: "Ol' Faithful",
        option2: brannST2,
        name2: "Brann's Saddle",
        option3: brannST3,
        name3: "Titan-Forged Grapnel",
        option4: brannST4,
        name4: "Sr. Excavator",
        option5: brannST5,
        name5: "Flo Slatebrand",
        option6: brannST6,
        name6: "Brann's Epic Egg",
      },
      heroPortrait: brann,
    },
    {
      id: 2,
      heroName: "Stelina",
      class: "Demon_Hunter",
      heroPower: demon_hunterHP1,
      hpSelect: {
        option1: demon_hunterHP1,
        name1: "Infernal Strike",
        option2: demon_hunterHP2,
        name2: "Outlander",
        option3: demon_hunterHP3,
        name3: "Illidari Strike",
      },
      sigTreasure: demon_hunterST1,
      stSelect: {
        option1: demon_hunterST1,
        name1: "Summoning Ritual",
        option2: demon_hunterST2,
        name2: "Mo'arg Outcast",
        option3: demon_hunterST3,
        name3: "Gift of the Legion",
        option4: demon_hunterST4,
        name4: "Binding Chains",
        option5: demon_hunterST5,
        name5: "Blade of Quickening",
        option6: demon_hunterST6,
        name6: "Traktamer Aelessa",
      },
      heroPortrait: demon_hunter,
    },
    {
      id: 3,
      heroName: "Drek'thar",
      class: "Neutral",
      heroPower: drektharHP1,
      hpSelect: {
        option1: drektharHP1,
        name1: "Warmaster's Frenzy",
        option2: drektharHP2,
        name2: "Harness the Elements",
        option3: drektharHP3,
        name3: "War Commands",
      },
      sigTreasure: drektharST1,
      stSelect: {
        option1: drektharST1,
        name1: "Valorous Display",
        option2: drektharST2,
        name2: "Elemental Chaos",
        option3: drektharST3,
        name3: "Pact of the Lich",
        option4: drektharST4,
        name4: "Magister Unchained",
        option5: drektharST5,
        name5: "Gift of the Heart",
        option6: drektharST6,
        name6: "For the Horde!",
      },
      heroPortrait: drekthar,
    },
    {
      id: 4,
      heroName: "Omu",
      class: "Druid",
      heroPower: druidHP1,
      hpSelect: {
        option1: druidHP1,
        name1: "Nature's Gift",
        option2: druidHP2,
        name2: "Invigorating Bloom",
        option3: druidHP3,
        name3: "Harvest Time!",
      },
      sigTreasure: druidST1,
      stSelect: {
        option1: druidST1,
        name1: "Warden's Insight",
        option2: druidST2,
        name2: "Moonbeast",
        option3: druidST3,
        name3: "Herding Horn",
        option4: druidST4,
        name4: "Marvelous Mycelium",
        option5: druidST5,
        name5: "Awakened Ancient",
        option6: druidST6,
        name6: "Zukara the Wild",
      },
      heroPortrait: druid,
    },
    {
      id: 5,
      heroName: "Elisea",
      class: "Druid,Priest",
      heroPower: eliseHP1,
      hpSelect: {
        option1: eliseHP1,
        name1: "Elise's Might",
        option2: eliseHP2,
        name2: "Drudic Teaching",
        option3: eliseHP3,
        name3: "Starseeker",
      },
      sigTreasure: eliseST1,
      stSelect: {
        option1: eliseST1,
        name1: "StarSeeker's Tools",
        option2: eliseST2,
        name2: "Elise's Machete",
        option3: eliseST3,
        name3: "Addarah",
        option4: eliseST4,
        name4: "Sr. Navigator",
        option5: eliseST5,
        name5: "Academic Research",
        option6: eliseST6,
        name6: "Staff of Renewal",
      },
      heroPortrait: elise,
    },
    {
      id: 6,
      heroName: "Finley",
      class: "Hunter,Warrior",
      heroPower: finleyHP1,
      hpSelect: {
        option1: finleyHP1,
        name1: "New 'Recruits'",
        option2: finleyHP2,
        name2: "Bubble Blower",
        option3: finleyHP3,
        name3: "Power Up!",
      },
      sigTreasure: finleyST1,
      stSelect: {
        option1: finleyST1,
        name1: "Finley's Pith Helmet",
        option2: finleyST2,
        name2: "Maxwell, Mighty Steed",
        option3: finleyST3,
        name3: "Trusilver Lance",
        option4: finleyST4,
        name4: "Sr.Scout",
        option5: finleyST5,
        name5: "Karl the Lost",
        option6: finleyST6,
        name6: "Scales of Justice",
      },
      heroPortrait: finley,
    },
    {
      id: 7,
      heroName: "Slate",
      class: "Hunter",
      heroPower: hunterHP1,
      hpSelect: {
        option1: hunterHP1,
        name1: "Survival Training",
        option2: hunterHP2,
        name2: "Death Games",
        option3: hunterHP3,
        name3: "Savage Secrets",
      },
      sigTreasure: hunterST1,
      stSelect: {
        option1: hunterST1,
        name1: "Slate's Syringe",
        option2: hunterST2,
        name2: "Bonecrusher",
        option3: hunterST3,
        name3: "Stalking Pride",
        option4: hunterST4,
        name4: "Deathstrider",
        option5: hunterST5,
        name5: "Carrot on a Stick",
        option6: hunterST6,
        name6: "Traktamer Aelessa",
      },
      heroPortrait: hunter,
    },
    {
      id: 8,
      heroName: "Mozaki",
      class: "Mage",
      heroPower: mageHP1,
      hpSelect: {
        option1: mageHP1,
        name1: "Wyrm Bold",
        option2: mageHP2,
        name2: "Secret Studies",
        option3: mageHP3,
        name3: "Frost Shards",
      },
      sigTreasure: mageST1,
      stSelect: {
        option1: mageST1,
        name1: "Wand of Dueling",
        option2: mageST2,
        name2: "Elemental Learning",
        option3: mageST3,
        name3: "Infinite Arcane",
        option4: mageST4,
        name4: "Embercaster",
        option5: mageST5,
        name5: "Yogg-tastic Tasties",
        option6: mageST6,
        name6: "Britz Blazebucket",
      },
      heroPortrait: mage,
    },
    {
      id: 9,
      heroName: "Turalyon",
      class: "Paladin",
      heroPower: paladinHP1,
      hpSelect: {
        option1: paladinHP1,
        name1: "From Golden Light",
        option2: paladinHP2,
        name2: "Bring on Recruits",
        option3: paladinHP3,
        name3: "Modest Aspirations",
      },
      sigTreasure: paladinST1,
      stSelect: {
        option1: paladinST1,
        name1: "Royal Greatsword",
        option2: paladinST2,
        name2: "Men at Arms",
        option3: paladinST3,
        name3: "Drocomuchanicas",
        option4: paladinST4,
        name4: "Favored Racer",
        option5: paladinST5,
        name5: "Humble Blessings",
        option6: paladinST6,
        name6: "Su Leadfoot",
      },
      heroPortrait: paladin,
    },
    {
      id: 10,
      heroName: "Illucia",
      class: "Priest",
      heroPower: priestHP1,
      hpSelect: {
        option1: priestHP1,
        name1: "Shadow Mend",
        option2: priestHP2,
        name2: "Mind Tether",
        option3: priestHP3,
        name3: "Call of Madness",
      },
      sigTreasure: priestST1,
      stSelect: {
        option1: priestST1,
        name1: "Fractured Spirits",
        option2: priestST2,
        name2: "Droplet of Insanity",
        option3: priestST3,
        name3: "Scion of the Deep",
        option4: priestST4,
        name4: "Shadow Word: Void",
        option5: priestST5,
        name5: "Hearld of the Scaled Ones",
        option6: priestST6,
        name6: "Joras Thuldoom",
      },
      heroPortrait: priest,
    },
    {
      id: 11,
      heroName: "Reno",
      class: "Mage,Rogue",
      heroPower: renoHP1,
      hpSelect: {
        option1: renoHP1,
        name1: "Amateur Mage",
        option2: renoHP2,
        name2: "'Relicologist'",
        option3: renoHP3,
        name3: "Arcane Craftiness",
      },
      sigTreasure: renoST1,
      stSelect: {
        option1: renoST1,
        name1: "Reno's Lucky Hat",
        option2: renoST2,
        name2: "Reno's Craft Lasso",
        option3: renoST3,
        name3: "Reno's Magical Torch",
        option4: renoST4,
        name4: "Sr. Tomb Diver",
        option5: renoST5,
        name5: "Lei Flamepaw",
        option6: renoST6,
        name6: "The Gattling Wand",
      },
      heroPortrait: reno,
    },
    {
      id: 12,
      heroName: "Lilian",
      class: "Rogue",
      heroPower: rogueHP1,
      hpSelect: {
        option1: rogueHP1,
        name1: "Roguish Maneuvers",
        option2: rogueHP2,
        name2: "Connections",
        option3: rogueHP3,
        name3: "Vile Concotion",
      },
      sigTreasure: rogueST1,
      stSelect: {
        option1: rogueST1,
        name1: "Deadly Weapons 101",
        option2: rogueST2,
        name2: "Nerubian Peddler",
        option3: rogueST3,
        name3: "Acquired Allies",
        option4: rogueST4,
        name4: "Ace in the Hole",
        option5: rogueST5,
        name5: "Green Tortollan Shell",
        option6: rogueST6,
        name6: "Britz Blazebucket",
      },
      heroPortrait: rogue,
    },
    {
      id: 13,
      heroName: "Fireheart",
      class: "Shaman",
      heroPower: shamanHP1,
      hpSelect: {
        option1: shamanHP1,
        name1: "Totemic Power",
        option2: shamanHP2,
        name2: "Ferocious Flurry",
        option3: shamanHP3,
        name3: "Stormcatcher",
      },
      sigTreasure: shamanST1,
      stSelect: {
        option1: shamanST1,
        name1: "Fluctuating Totem",
        option2: shamanST2,
        name2: "Tempest's Fury",
        option3: shamanST3,
        name3: "Invoke the Void",
        option4: shamanST4,
        name4: "Payload Totem Specialist",
        option5: shamanST5,
        name5: "Chaos Storm",
        option6: shamanST6,
        name6: "Zukara the Wild",
      },
      heroPortrait: shaman,
    },
    {
      id: 14,
      heroName: "Vanndar",
      class: "Neutral",
      heroPower: vanndarHP1,
      hpSelect: {
        option1: vanndarHP1,
        name1: "Promote!",
        option2: vanndarHP2,
        name2: "Send in the Scout",
        option3: vanndarHP3,
        name3: "Battle Tactics",
      },
      sigTreasure: vanndarST1,
      stSelect: {
        option1: vanndarST1,
        name1: "Forged in Light",
        option2: vanndarST2,
        name2: "Spymaster's Gambit",
        option3: vanndarST3,
        name3: "Stalker's Supplies",
        option4: vanndarST4,
        name4: "Rending Ambush",
        option5: vanndarST5,
        name5: "Devout Blessings",
        option6: vanndarST6,
        name6: "For the Alliance!",
      },
      heroPortrait: vanndar,
    },
    {
      id: 15,
      heroName: "Willow",
      class: "Warlock",
      heroPower: warlockHP1,
      hpSelect: {
        option1: warlockHP1,
        name1: "Dark Arts",
        option2: warlockHP2,
        name2: "Demon Blood",
        option3: warlockHP3,
        name3: "Soulcial Studies",
      },
      sigTreasure: warlockST1,
      stSelect: {
        option1: warlockST1,
        name1: "Impish Aid",
        option2: warlockST2,
        name2: "Gift of the Old Gods",
        option3: warlockST3,
        name3: "Killmox, the Banished One",
        option4: warlockST4,
        name4: "Demonizer",
        option5: warlockST5,
        name5: "Demonology 101",
        option6: warlockST6,
        name6: "Joras Thuldoom",
      },
      heroPortrait: warlock,
    },
    {
      id: 16,
      heroName: "Rattlegore",
      class: "Warrior",
      heroPower: warriorHP1,
      hpSelect: {
        option1: warriorHP1,
        name1: "No Guts, No Glory",
        option2: warriorHP2,
        name2: "Brusing",
        option3: warriorHP3,
        name3: "Magnetic Mines",
      },
      sigTreasure: warriorST1,
      stSelect: {
        option1: warriorST1,
        name1: "Auto-Armaments",
        option2: warriorST2,
        name2: "Collector's Ire",
        option3: warriorST3,
        name3: "Brewster, the Brutal",
        option4: warriorST4,
        name4: "Scrapmetal Demolitionist",
        option5: warriorST5,
        name5: "Spiked Arms",
        option6: warriorST6,
        name6: "Su Leadfoot",
      },
      heroPortrait: warrior,
    },
  ]);

  const [currentHero, setCurrentHero] = useState(heroes[0]);

  return (
    <>
      <Navbar
        heroes={heroes}
        currentHero={currentHero}
        setCurrentHero={setCurrentHero}
      ></Navbar>
    </>
  );
}

export default App;
