import { useState } from "react";
import "./App.css";

import { Navbar } from "./components/Navbar";

import {
  brann,
  brannHP1,
  brannHP2,
  brannHP3,
  demon_hunter,
  demon_hunterHP1,
  demon_hunterHP2,
  demon_hunterHP3,
  drekthar,
  drektharHP1,
  drektharHP2,
  drektharHP3,
  druid,
  druidHP1,
  druidHP2,
  druidHP3,
  elise,
  eliseHP1,
  eliseHP2,
  eliseHP3,
  finley,
  finleyHP1,
  finleyHP2,
  finleyHP3,
  hunter,
  hunterHP1,
  hunterHP2,
  hunterHP3,
  mage,
  mageHP1,
  mageHP2,
  mageHP3,
  paladin,
  paladinHP1,
  paladinHP2,
  paladinHP3,
  priest,
  priestHP1,
  priestHP2,
  priestHP3,
  reno,
  renoHP1,
  renoHP2,
  renoHP3,
  rogue,
  rogueHP1,
  rogueHP2,
  rogueHP3,
  shaman,
  shamanHP1,
  shamanHP2,
  shamanHP3,
  vanndar,
  vanndarHP1,
  vanndarHP2,
  vanndarHP3,
  warlock,
  warlockHP1,
  warlockHP2,
  warlockHP3,
  warrior,
  warriorHP1,
  warriorHP2,
  warriorHP3,
} from "./Images/index";

function App() {
  const [heroes] = useState([
    {
      id: 101,
      heroName: "Brann",
      class: "Brann",
      heroPower: brannHP1,
      hpSelect: {
        option1: brannHP1,
        name1: "Scattershot",
        option2: brannHP2,
        name2: "Well Equipped",
        option3: brannHP3,
        name3: "Dino Tracking",
      },
      sigTreasure: 1,
      heroPortrait: brann,
    },
    {
      id: 102,
      heroName: "Stelina",
      class: "Demon_Hunter",
      heroPower: demon_hunterHP1,
      hpSelect: {
        option1: demon_hunterHP1,
        name1: "Infernal Strike",
        option2: demon_hunterHP2,
        name2: "Outlander",
        option3: demon_hunterHP3,
        name3: "Illidari Strike", 
      },
      sigTreasure: 1,
      heroPortrait: demon_hunter,
    },
    {
      id: 103,
      heroName: "Drek'thar",
      class: "Neutral",
      heroPower: drektharHP1,
      hpSelect: {
        option1: drektharHP1,
        name1: "Warmaster's Frenzy",
        option2: drektharHP2,
        name2: "Harness the Elements",
        option3: drektharHP3,
        name3: "War Commands", 
      },
      sigTreasure: 1,
      heroPortrait: drekthar,
    },
    {
      id: 104,
      heroName: "Omu",
      class: "Druid",
      heroPower: druidHP1,
      hpSelect: {
        option1: druidHP1,
        name1: "Nature's Gift",
        option2: druidHP2,
        name2: "Invigorating Bloom",
        option3: druidHP3,
        name3: "Harvest Time!", 
      },
      sigTreasure: 1,
      heroPortrait: druid,
    },
    {
      id: 105,
      heroName: "Elisea",
      class: "Druid,Priest",
      heroPower: eliseHP1,
        hpSelect: {
          option1: eliseHP1,
          name1: "Elise's Might",
          option2: eliseHP2,
          name2: "Drudic Teaching",
          option3: eliseHP3,
          name3: "Starseeker",
        },
      sigTreasure: 1,
      heroPortrait: elise,
    },
    {
      id: 106,
      heroName: "Finley",
      class: "Hunter,Warrior",
      heroPower: finleyHP1,
        hpSelect: {
          option1: finleyHP1,
          name1: "New 'Recruits'",
          option2: finleyHP2,
          name2: "Bubble Blower",
          option3: finleyHP3,
          name3: "Power Up!",
        },
      sigTreasure: 1,
      heroPortrait: finley,
    },
    {
      id: 107,
      heroName: "Slate",
      class: "Hunter",
      heroPower: hunterHP1,
        hpSelect: {
          option1: hunterHP1,
          name1: "Survival Training",
          option2: hunterHP2,
          name2: "Death Games",
          option3: hunterHP3,
          name3: "Savage Secrets",
        },
      sigTreasure: 1,
      heroPortrait: hunter,
    },
    {
      id: 108,
      heroName: "Mozaki",
      class: "Mage",
      heroPower: mageHP1,
        hpSelect: {
          option1: mageHP1,
          name1: "Wyrm Bold",
          option2: mageHP2,
          name2: "Secret Studies",
          option3: mageHP3,
          name3: "Frost Shards",
        },
      sigTreasure: 1,
      heroPortrait: mage,
    },
    {
      id: 109,
      heroName: "Turalyon",
      class: "Paladin",
      heroPower: paladinHP1,
        hpSelect: {
          option1: paladinHP1,
          name1: "From Golden Light",
          option2: paladinHP2,
          name2: "Bring on Recruits",
          option3: paladinHP3,
          name3: "Modest Aspirations",
        },
      sigTreasure: 1,
      heroPortrait: paladin,
    },
    {
      id: 1010,
      heroName: "Illucia",
      class: "Priest",
      heroPower: priestHP1,
        hpSelect: {
          option1: priestHP1,
          name1: "Shadow Mend",
          option2: priestHP2,
          name2: "Mind Tether",
          option3: priestHP3,
          name3: "Call of Madness",
        },
      sigTreasure: 1,
      heroPortrait: priest,
    },
    {
      id: 1011,
      heroName: "Reno",
      class: "Mage,Rogue",
      heroPower: renoHP1,
        hpSelect: {
          option1: renoHP1,
          name1: "Amateur Mage",
          option2: renoHP2,
          name2: "'Relicologist'",
          option3: renoHP3,
          name3: "Arcane Craftiness",
        },
      sigTreasure: 1,
      heroPortrait: reno,
    },
    {
      id: 1012,
      heroName: "Lilian",
      class: "Rogue",
      heroPower: rogueHP1,
        hpSelect: {
          option1: rogueHP1,
          name1: "Roguish Maneuvers",
          option2: rogueHP2,
          name2: "Connections",
          option3: rogueHP3,
          name3: "Vile Concotion",
        },
      sigTreasure: 1,
      heroPortrait: rogue,
    },
    {
      id: 1013,
      heroName: "Fireheart",
      class: "Shaman",
      heroPower: shamanHP1,
        hpSelect: {
          option1: shamanHP1,
          name1: "Totemic Power",
          option2: shamanHP2,
          name2: "Ferocious Flurry",
          option3: shamanHP3,
          name3: "Stormcatcher",
        },
      sigTreasure: 1,
      heroPortrait: shaman,
    },
    {
      id: 1014,
      heroName: "Vanndar",
      class: "Neutral",
      heroPower: vanndarHP1,
        hpSelect: {
          option1: vanndarHP1,
          name1: "Promote!",
          option2: vanndarHP2,
          name2: "Send in the Scout",
          option3: vanndarHP3,
          name3: "Battle Tactics",
        },
      sigTreasure: 1,
      heroPortrait: vanndar,
    },
    {
      id: 1015,
      heroName: "Willow",
      class: "Warlock",
      heroPower: warlockHP1,
        hpSelect: {
          option1: warlockHP1,
          name1: "Dark Arts",
          option2: warlockHP2,
          name2: "Demon Blood",
          option3: warlockHP3,
          name3: "Soulcial Studies",
        },
      sigTreasure: 1,
      heroPortrait: warlock,
    },
    {
      id: 1016,
      heroName: "Rattlegore",
      class: "Warrior",
      heroPower: warriorHP1,
        hpSelect: {
          option1: warriorHP1,
          name1: "No Guts, No Glory",
          option2: warriorHP2,
          name2: "Brusing",
          option3: warriorHP3,
          name3: "Magnetic Mines",
        },
      sigTreasure: 1,
      heroPortrait: warrior,
    },
  ]);

  const [currentHero, setCurrentHero] = useState(heroes[0]);

  return (
    <>
      <Navbar
        heroes={heroes}
        currentHero={currentHero}
        setCurrentHero={setCurrentHero}
      ></Navbar>
    </>
  );
}

export default App;
